# Generated by Django 5.1.1 on 2024-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer')], default='CREDIT_CARD', max_length=20),
        ),
    ]
